# -*- coding: utf-8 -*-
"""TIK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ov1J-mo3j0BNN1j6A3GpVbE8ioQ3rPlu

# Програмна система семантичного розрізнення сигналів у дегенерованих асиметричних каналах

## Анотація
У роботі представлено програмну систему для відновлення даних у каналах зв'язку з виродженою матрицею передачі. Виявлено критичні обмеження класичних статистичних методів при нульовому визначнику канальної матриці. Запропоновано семантичний підхід на основі векторних представлень (embeddings), що дозволяє усувати невизначеність при збігу прийнятих сигналів. Результати підтверджено статистично.

## Мета роботи
Зменшення залишкової ентропії та підвищення точності розрізнення станів у вироджених каналах зв'язку шляхом використання геометричної семантики векторних представлень для усунення структурної невизначеності.

## 1. Теоретичне обґрунтування та проблематика

Класична теорія інформації описує канал через матрицю ймовірностей $P(Y|X)$. Проте в реальних інженерних системах виникають умови, за яких визначник цієї матриці $\det(P)$ дорівнює нулю.

### Основні обмеження:
*   **Втрата кодової відстані:** Якщо канал відображає різні вхідні сигнали $X_1$ та $X_2$ в ідентичні вихідні розподіли, кодова відстань Хеммінга між ними стає нульовою.
*   **Ентропійний бар'єр посимвольного аналізу:** В умовах виродженості матриці вхідні стани стають статистично нерозрізнюваними. Це призводить до зростання залишкової ентропії $H(X|Y)$ до максимуму, оскільки спостережуваний сигнал перестає нести інформацію для вибору між ідентичними станами системи.

## 2. Сутність семантичного підходу
Запропонований підхід базується на **геометричній семантиці** та векторних представленнях (**Embeddings**).

Замість аналізу окремих символів, система відображає послідовність станів у багатовимірний латентний простір. Це дозволяє «розклеїти» вироджені рядки матриці за рахунок аналізу **«траєкторії» сигналу в часі**, додаючи системі новий вимір ідентифікації, недоступний класичному декодеру.

## 3. Моделювання виродженого каналу та генерація послідовностей

Для експериментальної перевірки розроблено програмний комплекс, що моделює передачу дискретних повідомлень через канал з дефіцитом рангу матриці переходу.

### Характеристики моделі:
*   **Вироджена матриця $P(Y|X)$:** Ми створюємо умови, за яких різні вхідні стани $X_i$ мають ідентичні умовні розподіли вихідних символів $Y_j$. Це робить стани нерозрізнюваними для будь-якого декодера, що працює за принципом максимуму правдоподібності (ML).
*   **Асиметрія джерела:** Вхідні стани генеруються з різною апріорною ймовірністю. Це дозволяє дослідити поведінку статистичних методів в умовах, коли апріорні дані починають домінувати над спостережуваним сигналом.
*   **Часова зв'язність (Контекст):** На відміну від класичної моделі без пам'яті, ми вводимо залежність поточного стану від попередніх. Це створює "семантичну траєкторію", яку можна використати для усунення невизначеності.

#### Експериментальні вибірки:
1.  **Структурована послідовність:** Містить латентні часові залежності між сигналами.
2.  **Контрольна вибірка (Ентропійний максимум):** Послідовність незалежних подій (Memoryless source), де семантичний підхід теоретично не може надати переваги.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def generate_complex_degenerate_matrix(n=10, rank=5):
    """Автоматична генерація виродженої матриці 10x10 природним шляхом"""
    A = np.random.rand(n, rank)
    B = np.random.rand(rank, n)
    matrix = np.dot(A, B)
    return matrix / matrix.sum(axis=1)[:, None]

# 1. Ініціалізація системи
N_STATES = 10
CHANNEL_MATRIX = generate_complex_degenerate_matrix(N_STATES, rank=8)

class AdvancedInfoGenerator:
    def __init__(self, matrix, n_states):
        self.matrix = matrix
        self.n_states = n_states

    def generate(self, size=100000, is_structured=True):
        X, Y = [], []
        # СТРАТЕГІЯ: Система "пар" (X0->X5, X1->X6...)
        # Це набагато складніша семантика для розпізнавання
        curr_x = np.random.randint(5)

        for _ in range(size):
            if is_structured:
                # Якщо зараз стан від 0 до 4, наступним МАЄ бути відповідний стан від 5 до 9
                if curr_x < 5:
                    next_x = curr_x + 5
                else:
                    next_x = np.random.randint(5) # Потім новий випадковий запит
            else:
                next_x = np.random.choice(self.n_states)

            y_val = np.random.choice(self.n_states, p=self.matrix[next_x])
            X.append(next_x)
            Y.append(float(y_val))
            curr_x = next_x

        return np.array(X), np.array(Y).reshape(-1, 1)

# 2. Генеруємо дані з новою логікою
gen = AdvancedInfoGenerator(CHANNEL_MATRIX, N_STATES)
X_train, Y_train = gen.generate(size=100000, is_structured=True)
X_test, Y_test = gen.generate(size=20000, is_structured=True)
X_noise, Y_noise = gen.generate(size=20000, is_structured=False)

print(f"--- ДАТАСЕТ З ПАРАМИ ЗАПИТ-ВІДПОВІДЬ ГОТОВИЙ ---")
print(f"Математичний ранг матриці: {np.linalg.matrix_rank(CHANNEL_MATRIX)}")

"""## 4. Побудова семантичного простору та векторне розрізнення

На цьому етапі ми переходимо від посимвольного аналізу до **геометричної семантики**.

### Ключові компоненти моделі:
*   **Шар векторних представлень (Embeddings):** Кожен з 10 вхідних станів відображається у 16-вимірний латентний простір. Це дозволяє системі оперувати не просто номерами сигналів, а їхніми семантичними векторами.
*   **Геометрична метрика:** Розрізнення станів у латентному просторі базується на **косинусній відстані (Cosine Similarity)**. Це дозволяє моделі групувати сигнали за їхнім "сенсором" (контекстом), ігноруючи амплітудний шум.
*   **Рекурентна архітектура (GRU):** Використовується для аналізу послідовностей довжиною $L=10$. Модель вивчає "траєкторію" вхідного сигналу, що дозволяє ідентифікувати істинний стан $X$ навіть тоді, коли миттєве значення $Y$ є виродженим.
*   **Оптимізація:** Навчання проводиться для максимізації взаємної інформації між вхідною послідовністю та виходом декодера.

Цей підхід дозволяє "розклеїти" стани з однаковими ймовірнісними профілями за рахунок аналізу часових кореляцій, які ігноруються класичними методами.

"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import matplotlib.pyplot as plt

# 1. Налаштування пристрою
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if device.type == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# 2. Функція підготовки послідовностей (seq_len=20)
def to_sequences(Y, X, seq_len=20):
    # Використовуємо numpy для швидкості, потім в тензори
    Y_seq = [Y[i:i+seq_len].flatten() for i in range(len(Y)-seq_len)]
    X_target = [X[i+seq_len-1] for i in range(len(X)-seq_len)]
    return torch.LongTensor(np.array(Y_seq)), torch.LongTensor(np.array(X_target))

print("Підготовка даних...")
train_in, train_out = to_sequences(Y_train, X_train, seq_len=20)
test_in, test_out = to_sequences(Y_test, X_test, seq_len=20)

# Створюємо завантажувач для батчів (щоб уникнути OutOfMemory)
train_loader = DataLoader(TensorDataset(train_in, train_out), batch_size=2048, shuffle=True)

# 3. Модель з Embeddings та 2-шаровим GRU
class SemanticDecoder(nn.Module):
    def __init__(self, n_states, embed_dim=8):
        super().__init__()
        self.embeddings = nn.Embedding(n_states, embed_dim)
        # 2 шари GRU + Dropout для стабільності
        self.rnn = nn.GRU(embed_dim, 64, num_layers=2, batch_first=True, dropout=0.1)
        self.fc = nn.Linear(64, n_states)

    def forward(self, x):
        x = self.embeddings(x)
        _, h = self.rnn(x)
        return self.fc(h[-1])

# Ініціалізація
model = SemanticDecoder(N_STATES, embed_dim=8).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# 4. Безпечний цикл навчання (з батчами)
print(f"Починаємо навчання (Batching active)...")
model.train()
for epoch in range(150): # 150 епох для глибокого вивчення семантики
    epoch_loss = 0
    for b_in, b_out in train_loader:
        b_in, b_out = b_in.to(device), b_out.to(device)
        optimizer.zero_grad()
        outputs = model(b_in)
        loss = criterion(outputs, b_out)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()

    if epoch % 30 == 0:
        print(f"Epoch {epoch}, Loss: {epoch_loss/len(train_loader):.4f}")

print("\nНавчання завершено!")

# 5. ВІЗУАЛІЗАЦІЯ КЛАСТЕРІВ (Scatter Plot)
weights = model.embeddings.weight.detach().cpu().numpy()
plt.figure(figsize=(10, 7))
for i in range(N_STATES):
    color = 'red' if i < 5 else 'blue'
    plt.scatter(weights[i, 0], weights[i, 1], c=color, s=100)
    plt.text(weights[i, 0]+0.01, weights[i, 1]+0.01, f'X{i}', fontsize=12)
plt.grid(True, alpha=0.3)
plt.title("Фінальна геометрична кластеризація станів у 2D")
plt.show()

import math
from sklearn.metrics import accuracy_score
from scipy import stats
import seaborn as sns
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

# 1. Оновлена архітектура моделі
class SemanticDecoder(nn.Module):
    def __init__(self, n_states, embed_dim=8):
        super().__init__()
        self.embeddings = nn.Embedding(n_states, embed_dim)
        # Додаємо потужності: 2 шари GRU та Dropout для стабільності
        self.rnn = nn.GRU(embed_dim, 64, num_layers=2, batch_first=True, dropout=0.1)
        self.fc = nn.Linear(64, n_states)

    def forward(self, x):
        x = self.embeddings(x)
        out, _ = self.rnn(x)
        return self.fc(out[:, -1, :])

def calculate_conditional_entropy(y_pred_probs):
    epsilon = 1e-12
    entropy = -np.mean(np.sum(y_pred_probs * np.log2(y_pred_probs + epsilon), axis=1))
    return entropy

def run_scientific_experiment_final(n_runs=5):
    sem_accs, class_accs, sem_entropies = [], [], []
    S_LEN = 20

    # 1. Готуємо дані (вони поки на CPU)
    train_in_f, train_out_f = to_sequences(Y_train, X_train, seq_len=S_LEN)
    test_in_f, test_out_f = to_sequences(Y_test, X_test, seq_len=S_LEN)

    # Створюємо DataLoader
    train_loader = DataLoader(TensorDataset(train_in_f, train_out_f), batch_size=2048, shuffle=True)

    temp_preds_len = len(test_out_f)
    y_true_local = test_out_f.numpy()
    y_obs_classical = Y_test[S_LEN-1 : S_LEN-1 + temp_preds_len].flatten()

    print(f"Починаємо фінальну серію (Rank=8, Batching active)...")

    for run in range(n_runs):
        run_model = SemanticDecoder(N_STATES, embed_dim=8).to(device)
        run_opt = optim.Adam(run_model.parameters(), lr=0.001)

        run_model.train()
        for epoch in range(150): # 150 епох
            for b_in, b_out in train_loader:
                # ПЕРЕНОСИМО БАТЧ НА GPU
                b_in, b_out = b_in.to(device), b_out.to(device)
                run_opt.zero_grad()
                loss = nn.CrossEntropyLoss()(run_model(b_in), b_out)
                loss.backward()
                run_opt.step()

        run_model.eval()
        with torch.no_grad():
            test_outputs = []
            # Тестуємо теж батчами, щоб не було OutOfMemory
            for i in range(0, len(test_in_f), 2048):
                batch_test = test_in_f[i:i+2048].to(device) # ПЕРЕНОСИМО НА GPU
                test_outputs.append(run_model(batch_test))

            outputs = torch.cat(test_outputs)
            probs = torch.softmax(outputs, dim=1).cpu().numpy()
            preds = np.argmax(probs, axis=1)

            acc = accuracy_score(y_true_local, preds)
            ent = calculate_conditional_entropy(probs)
            sem_accs.append(acc)
            sem_entropies.append(ent)

            c_preds = [np.argmax(CHANNEL_MATRIX[:, int(y)]) for y in y_obs_classical]
            class_accs.append(accuracy_score(y_true_local, c_preds))

        print(f"Запуск {run+1}: Accuracy={acc:.4f}, Entropy={ent:.4f}")

    return sem_accs, class_accs, sem_entropies, run_model


# ВИКОНАННЯ
sem_accs, class_accs, sem_entropies, last_model = run_scientific_experiment_final(5)

# ЗВІТ ТА ГРАФІК
t_stat, p_val = stats.ttest_ind(sem_accs, class_accs)
h_baseline = math.log2(N_STATES)

print(f"\n--- ПІДСУМКОВИЙ НАУКОВИЙ ЗВІТ ---")
print(f"Точність (Семантика): {np.mean(sem_accs):.4f} ± {np.std(sem_accs):.4f}")
print(f"Точність (Класика):   {np.mean(class_accs):.4f}")
print(f"Залишкова ентропія:  {np.mean(sem_entropies):.4f} біт (Зменшено з {h_baseline:.2f} біт)")
print(f"T-test p-value: {p_val:.10f} ({'СТАТИСТИЧНО ЗНАЧУЩО' if p_val < 0.05 else 'НЕЗНАЧУЩО'})")

# 4. ВІЗУАЛІЗАЦІЯ КЛАСТЕРІВ
weights = last_model.embeddings.weight.detach().cpu().numpy()
plt.figure(figsize=(10, 7))
for i in range(N_STATES):
    color = 'red' if i < 5 else 'blue'
    plt.scatter(weights[i, 0], weights[i, 1], c=color, s=100)
    plt.text(weights[i, 0]+0.01, weights[i, 1]+0.01, f'X{i}', fontsize=12)
plt.grid(True, alpha=0.3)
plt.title("Фінальний геометричний розподіл станів")
plt.show()